server:
  port: 8090

jwt:
#  secret: f3f42ea931044d1384c07bcb68208fa5b6cdb6cd697
  secret: rgx8o8VQGuDa2AqCHSgVOD5G68Ld5YYM7N7THmvLIKcq8ui
  lifetime: 30m

spring:
  application:
    name: Task
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5454/task
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
logging:
  level:
    root: info
#    root: debug