server:
  port: 8090

jwt:
  secret: f3f42ea9-3104-4d13-84c0-7bcb68202f16
  lifetime: 30m

spring:
  application:
    name: Task
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5454/task
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
logging:
  level:
    root: info